// <auto-generated />
using System;
using Inventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260915144021_AgregarImagenBinariaProducto")]
    partial class AgregarImagenBinariaProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreArea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoArea")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Entidad", "EntidadId");

                    b.ToTable("Auditoria", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCategoria")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Conteo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadContada")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("ContadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaConteo")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroConteo")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("SesionConteo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("SesionConteo", "ProductoId", "UbicacionId", "NumeroConteo")
                        .IsUnique();

                    b.ToTable("Conteo", null, t =>
                        {
                            t.HasCheckConstraint("CK_Conteo_Cantidad", "[CantidadContada] >= 0");

                            t.HasCheckConstraint("CK_Conteo_Numero", "[NumeroConteo] >= 1");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CantidadEfectiva")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaRetornoEsperada")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("MovimientoOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Retorna")
                        .HasColumnType("bit");

                    b.Property<int?>("SolicitudDetalleId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.Property<string>("UbicacionExterna")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovimientoOrigenId");

                    b.HasIndex("NumeroMovimiento")
                        .IsUnique();

                    b.HasIndex("SolicitudDetalleId");

                    b.HasIndex("ProductoId", "FechaMovimiento");

                    b.HasIndex("UbicacionId", "ProductoId");

                    b.ToTable("Movimiento", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movimiento_Cantidad", "[Cantidad] > 0");

                            t.HasCheckConstraint("CK_Movimiento_NoAutoOrigen", "[MovimientoOrigenId] IS NULL OR [MovimientoOrigenId] <> [Id]");

                            t.HasCheckConstraint("CK_Movimiento_OrigenSoloEntrada", "[MovimientoOrigenId] IS NULL OR [TipoMovimiento] = 1");

                            t.HasCheckConstraint("CK_Movimiento_RetornaSoloSalida", "[TipoMovimiento] = 2 OR ([Retorna] = 0 AND [UbicacionExterna] IS NULL AND [FechaRetornoEsperada] IS NULL)");

                            t.HasCheckConstraint("CK_Movimiento_Signo", "([TipoMovimiento] IN (1,3) AND [CantidadEfectiva] = [Cantidad]) OR ([TipoMovimiento] IN (2,4) AND [CantidadEfectiva] = -[Cantidad])");

                            t.HasCheckConstraint("CK_Movimiento_SolicitudSoloSalida", "[SolicitudDetalleId] IS NULL OR [TipoMovimiento] = 2");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permiso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "productos.ver",
                            Descripcion = "Ver el catálogo de productos y su existencia",
                            Modulo = "Productos"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "productos.crear",
                            Descripcion = "Crear productos nuevos",
                            Modulo = "Productos"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "productos.editar",
                            Descripcion = "Editar productos existentes",
                            Modulo = "Productos"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "productos.desactivar",
                            Descripcion = "Desactivar productos",
                            Modulo = "Productos"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "movimientos.ver",
                            Descripcion = "Ver el historial de movimientos",
                            Modulo = "Movimientos"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "movimientos.entrada",
                            Descripcion = "Registrar entradas de stock",
                            Modulo = "Movimientos"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "movimientos.salida",
                            Descripcion = "Registrar salidas de stock",
                            Modulo = "Movimientos"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "movimientos.ajuste",
                            Descripcion = "Registrar ajustes positivos/negativos",
                            Modulo = "Movimientos"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "movimientos.devolucion",
                            Descripcion = "Registrar devoluciones de préstamo",
                            Modulo = "Movimientos"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "solicitudes.ver",
                            Descripcion = "Ver solicitudes de material",
                            Modulo = "Solicitudes"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "solicitudes.crear",
                            Descripcion = "Crear solicitudes de material",
                            Modulo = "Solicitudes"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "solicitudes.aprobar",
                            Descripcion = "Aprobar solicitudes pendientes",
                            Modulo = "Solicitudes"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "solicitudes.rechazar",
                            Descripcion = "Rechazar solicitudes pendientes",
                            Modulo = "Solicitudes"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "solicitudes.entregar",
                            Descripcion = "Registrar la entrega de una solicitud aprobada",
                            Modulo = "Solicitudes"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "conteos.ver",
                            Descripcion = "Ver conteos por sesión",
                            Modulo = "Conteo físico"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "conteos.registrar",
                            Descripcion = "Registrar conteos",
                            Modulo = "Conteo físico"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "categorias.ver",
                            Descripcion = "Ver categorías",
                            Modulo = "Categorías"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "categorias.crear",
                            Descripcion = "Crear categorías",
                            Modulo = "Categorías"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "areas.ver",
                            Descripcion = "Ver áreas",
                            Modulo = "Áreas"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "areas.crear",
                            Descripcion = "Crear áreas",
                            Modulo = "Áreas"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "ubicaciones.ver",
                            Descripcion = "Ver ubicaciones",
                            Modulo = "Ubicaciones"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "ubicaciones.crear",
                            Descripcion = "Crear ubicaciones",
                            Modulo = "Ubicaciones"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "usuarios.gestionar",
                            Descripcion = "Crear y editar usuarios",
                            Modulo = "Administración"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "roles.gestionar",
                            Descripcion = "Crear roles y asignarles permisos",
                            Modulo = "Administración"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "categorias.editar",
                            Descripcion = "Editar categorías existentes",
                            Modulo = "Categorías"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "areas.editar",
                            Descripcion = "Editar áreas existentes",
                            Modulo = "Áreas"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("ClaveProducto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CostoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImagenContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ImagenData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClaveProducto")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("Producto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Producto_Costo", "[CostoUnitario] IS NULL OR [CostoUnitario] >= 0");

                            t.HasCheckConstraint("CK_Producto_StockMin", "[StockMinimo] >= 0");

                            t.HasCheckConstraint("CK_Producto_Unidad", "[UnidadMedida] IN ('UNI','CAJA','PQTS')");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("Rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Acceso completo, incluida la gestión de usuarios y roles.",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Opera el día a día: productos, movimientos, solicitudes y conteo. Sin gestión de catálogos ni usuarios.",
                            Nombre = "Operador"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Solo lectura en todos los módulos.",
                            Nombre = "Consulta"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 3
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 4
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 12
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 13
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 14
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 16
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 18
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 19
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 20
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 21
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 22
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 23
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 24
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 25
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 26
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 6
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 7
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 8
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 9
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 11
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 14
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 16
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 19
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 21
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 1
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 5
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 10
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 15
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 17
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 19
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 21
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AprobadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NumeroSolicitud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SolicitadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("NumeroSolicitud")
                        .IsUnique();

                    b.ToTable("Solicitud", null, t =>
                        {
                            t.HasCheckConstraint("CK_Solicitud_MotivoRechazo", "[Estado] <> 4 OR [MotivoRechazo] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.SolicitudDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadAprobada")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CantidadEntregada")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CantidadSolicitada")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SolicitudId", "ProductoId")
                        .IsUnique();

                    b.ToTable("SolicitudDetalle", null, t =>
                        {
                            t.HasCheckConstraint("CK_SolicitudDetalle_Aprobada", "[CantidadAprobada] IS NULL OR [CantidadAprobada] <= [CantidadSolicitada]");

                            t.HasCheckConstraint("CK_SolicitudDetalle_Entregada", "[CantidadEntregada] >= 0");

                            t.HasCheckConstraint("CK_SolicitudDetalle_Solicitada", "[CantidadSolicitada] > 0");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoUbicacion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Lado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoUbicacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUbicacion")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("Ubicacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ubicacion_Nivel", "([TipoUbicacion] = 1 AND [Nivel] IS NOT NULL) OR ([TipoUbicacion] = 2 AND [Nivel] IS NULL)");
                        });
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoLoginEn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Conteo", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Movimiento", "MovimientoOrigen")
                        .WithMany()
                        .HasForeignKey("MovimientoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Inventory.Domain.Entities.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entities.SolicitudDetalle", "SolicitudDetalle")
                        .WithMany("Movimientos")
                        .HasForeignKey("SolicitudDetalleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Inventory.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MovimientoOrigen");

                    b.Navigation("Producto");

                    b.Navigation("SolicitudDetalle");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.SolicitudDetalle", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Detalles")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.SolicitudDetalle", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
